### PR TITLE
enable word highlighting for dance selection

### PR DESCRIPTION
**Pull request by kabouzeid**
Does the same as VSCodeVim https://github.com/VSCodeVim/Vim/blob/6d76ea60d3ce97a20cc3c22ebf58a2d61e7705db/src/mode/modeHandler.ts#L1648

### CODE REVIEW

**Comment by kabouzeid** [comment]
**Before**

https://user-images.githubusercontent.com/7303830/201115821-626ede33-47fd-4bc7-a35d-bee438513dc0.mov

**After**

https://user-images.githubusercontent.com/7303830/201115839-f3732476-6dc4-4e85-b0af-1b25c6bfa9ec.mov

**Comment by Delapouite** [comment]
Thanks for taking the time to upload videos :+1:

**Review by 71 — APPROVED** [review]
Oh, awesome, thanks! Can you add a comment similar to the one in VSCodeVim to explain what this line does?

**Comment by kabouzeid** [comment]
Hmm, I'm not sure what the comment should say that is not already in the name of the command? Do you have a suggestion?

**Comment by 71** [comment]
Fair enough, it'd be a little redundant.

**Pull request merged**
