### PR TITLE
Correct multipaste behaviour

### LINKED ISSUE #81: Pasting multiple selections with <alt-p>
In Kakoune, if you copy multiple items and then collapse the selection to one item, <alt-p> pastes every item. With Dance, it only pastes the first. In VSCode, the default Paste with multiple cursors has the same behavior as Kakoune, so I can use the builtin Paste to get what I want. 

If there are three selections copied and two current selections, both VSCode's Paste and Kakoune's <alt-p> insert the three selections in two places. If the number of copied selections matches the number of current selections, it inserts one copy after each of the selections.

### PR DESCRIPTION
**Pull request by pomdtr**
Closes #81 

I would gladly add unit test, but i am unable to run them on my machine. They all return :   
```
148) Running commands
       dance/test/suite/commands/select.word.edge      : mutation multi.0       > multi.4       is applied correctly:
     TypeError: Cannot set property '_selectionBehavior' of undefined
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:89:36
      at Generator.next (<anonymous>)
      at /Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (out/test/suite/commands.test.js:4:12)
      at testCommands (out/test/suite/commands.test.js:67:12)
      at Context.<anonymous> (test/suite/commands.test.ts:268:17)
      at Generator.next (<anonymous>)
      at fulfilled (out/test/suite/commands.test.js:5:58)
```

### CODE REVIEW

**Comment by 71** [comment]
Looks like [`extensionState`](https://github.com/71/dance/blob/2d0c66e8eaf0831a6d6e2cb5effb4171607d6cf4/src/extension.ts#L14) is undefined, which means that `activate` wasn't called. In my case, the extension is always `activate`d before the tests start running (even on slower computers) but in your case the extension does not appear to get `activate`d.

Did you run the tests using `VS Code > Run > Run Extension Tests`?

**Comment by pomdtr** [comment]
> Did you run the tests using VS Code > Run > Run Extension Tests?
I was using the terminal to launch the test !

I still have some issues with the tests on master. Indent test failure are likely due to my settings, but i'm not sure i'm experiencing the correct behaviour for the select tests.

<details>
<summary>Test logs</summary>

```
  189 passing (4s)
  3 pending
  17 failing
  1) Running commands
       dance/test/suite/commands/indent                : mutation 0        > 0.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      -    jumps over the lazy
      +  The quick brown fox
      +  jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  2) Running commands
       dance/test/suite/commands/indent                : mutation 1        > 1.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      -    jumps over the lazy
      +  The quick brown fox
      +  jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  3) Running commands
       dance/test/suite/commands/indent                : mutation 2        > 2.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  4) Running commands
       dance/test/suite/commands/indent                : mutation 3        > 3.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  5) Running commands
       dance/test/suite/commands/indent                : mutation 4        > 4.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  6) Running commands
       dance/test/suite/commands/indent.caret          : mutation 0        > 0.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      -    jumps over the lazy
      +  The quick brown fox
      +  jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  7) Running commands
       dance/test/suite/commands/indent.caret          : mutation 1        > 1.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      -    jumps over the lazy
      +  The quick brown fox
      +  jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  8) Running commands
       dance/test/suite/commands/indent.caret          : mutation 2        > 2.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  9) Running commands
       dance/test/suite/commands/indent.caret          : mutation 3        > 3.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  10) Running commands
       dance/test/suite/commands/indent.caret          : mutation 4        > 4.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  11) Running commands
       dance/test/suite/commands/indent.caret          : mutation 5        > 5.indent is applied correctly:

      AssertionError [ERR_ASSERTION]: Document text is not as expected.
      + expected - actual

      -    The quick brown fox
      +  The quick brown fox
       jumps over the lazy
       dog.
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:130:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  12) Running commands
       dance/test/suite/commands/objects.sentence      : mutation 5              > 5.select       is applied correctly:

      AssertionError [ERR_ASSERTION]: Expected Selection #2 to match ('>' is anchor, '|' is cursor).
      + expected - actual

       I'm a sentence terminated by two line breaks plus one more
      +>
       
      ->
       |
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:147:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  13) Running commands
       dance/test/suite/commands/objects.sentence      : mutation 6              > 6.toEnd        is applied correctly:

      AssertionError [ERR_ASSERTION]: (Actual Selection #0 is at same spots in document as expected, but with different numbers)
      + expected - actual

           "_character": 0
           "_line": 1
         }
         "_anchor": {
      -    "_character": 9007199254740991
      +    "_character": 33
           "_line": 0
         }
         "_end": {
           "_character": 0
           "_line": 1
         }
         "_start": {
      -    "_character": 9007199254740991
      +    "_character": 33
           "_line": 0
         }
       }
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:149:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  14) Running commands
       dance/test/suite/commands/select                : mutation 6                          > 6.select.line              is applied correctly:

      AssertionError [ERR_ASSERTION]: Expected Selection #0 to match ('>' is anchor, '|' is cursor).
      + expected - actual

      -hello
      ->world|
      +>hello
      +|world
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:147:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  15) Running commands
       dance/test/suite/commands/select                : mutation 6                          > 6.select.line.extend       is applied correctly:

      AssertionError [ERR_ASSERTION]: Expected Selection #0 to match ('>' is anchor, '|' is cursor).
      + expected - actual

      -hello
      ->world|
      +hello>
      +|world
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:147:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  16) Running commands
       dance/test/suite/commands/select                : mutation 7                          > 7.select.line.extend       is applied correctly:

      AssertionError [ERR_ASSERTION]: Expected Selection #0 to match ('>' is anchor, '|' is cursor).
      + expected - actual

      -hello
      ->w|orld
      +hello>
      +w|orld
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:147:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

  17) Running commands
       dance/test/suite/commands/select.copy           : mutation 14 > 15 is applied correctly:

      AssertionError [ERR_ASSERTION]: Expected Selection #1 to match ('>' is anchor, '|' is cursor).
      + expected - actual

       ab
      -cd>|
      -efg
      +cd>
      +|efg
       hi
      
      at /Users/a.lacoin/Documents/dance/test/suite/commands.test.ts:147:14
      at Generator.next (<anonymous>)
      at fulfilled (/Users/a.lacoin/Documents/dance/out/test/suite/commands.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)


```
</details>

**Comment by 71** [comment]
Why do you think indent issues are due to your settings? I'd like to make the tests user settings-agnostic.

Other than indent tests, the six other tests also fail on my end. They're what we'd like to have, but we haven't gotten around fixing them yet.

**Comment by pomdtr** [comment]
> Why do you think indent issues are due to your settings? I'd like to make the tests user settings-agnostic.

The indent command depends on the editor tab size, this is why my indent test are failing

```typescript
    const indent = editor.options.insertSpaces === true
                    ? ' '.repeat(editor.options.tabSize as number)
                    : '\t'
```

**Pull request closed without merging**
