### PR TITLE
correct isAlphaWord to handle non latin characters

### PR DESCRIPTION
**Pull request by pomdtr**
This pull request allows to reuse the editor native word separators.

### CODE REVIEW

**Comment by 71** [comment]
Good catch! I'm in a middle of a large refactor and I'd like to cache the value of `editor.wordSeparators` so I won't use this PR, but thanks for the idea!

**Comment by pomdtr** [comment]
Ok, I look forward to be able to use the new version ! I'm currently trying to implement the views command using the `editorScroll` and `revealLine` functions, is it also in the scope of your future change ?

**Comment by 71** [comment]
I haven't planned anything on that end, but everything that deals with selections will have to be changed, so you may want to wait a little in order to avoid having to change things afterward.

**Comment by 71** [comment]
As for `trimWhitespace`, it is implemented in the refactor.

**Pull request closed without merging**
