### PR TITLE
Add support for "goto last buffer modification"

### PR DESCRIPTION
**Pull request by vbn**
I was missing "goto last buffer modification" feature so I implemented it. It's probably not very clean, so I would appreciate feedback.

I read the discussion on #7 but I couldn't figure out a way to use existing features to implement it in a better way.

Also fixed a couple of issues I found when debugging this feature.

### CODE REVIEW

**Comment by 71** [comment]
Hey there, and thanks for the help!

It does seem a little hacky; I'd rather have `lastLocations` on `Extension`, and I'd rather you use `WeakMap` instead of `Map`. Also, isn't there a problem with using `TextEditor` as a key? I know VS Code often uses different instances of `vscode.TextEditor`, so even though `vscode.TextDocument` can be kept as a key because it never changes as long as the file is open, this might not be the case for `vscode.TextEditor`.

The other changes are welcome, but unfortunately conflict in part with the work we have going in `unstable`. It probably won't matter, though.

**Comment by vbn** [comment]
Thanks for the review.

> It does seem a little hacky; I'd rather have lastLocations on Extension, and I'd rather you use WeakMap instead of Map. Also, isn't there a problem with using TextEditor as a key? I know VS Code often uses different instances of vscode.TextEditor, so even though vscode.TextDocument can be kept as a key because it never changes as long as the file is open, this might not be the case for vscode.TextEditor.

The reason `TextEditor` is the key is because the callback `executeGoto` provides the `editor` value which can be readily looked at. So I wanted to optimize for that. I can switch to `vscode.TextDocument`.

> The other changes are welcome, but unfortunately conflict in part with the work we have going in unstable. It probably won't matter, though.

I just found the issues as I was working on them and since I had a fix for them, I wanted to send a review. I can drop the changes if necessary.

> Edit: I didn't see that correctly, but it looks like you're already taking care of deleting useless editors. I do recommend using WeakMap instead.

I will switch to WeakMap instead. It's not a lot of work.

**Comment by 71** [comment]
I'm going to implement this on top of the `unstable` branch, which is very different from the `master` branch. Sorry your modifications won't be merged, but the feature should be added very soon.

**Comment by 71** [comment]
This is now implemented in `unstable`: 2591a09fce6eeb62705abed4a78d1004bfefffc7.

**Comment by vbn** [comment]
Thanks for adding the support. Hoping to see a release soonish with this.

**Pull request closed without merging**
